import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.security.KeyFactory;
import java.security.KeyPair;
import java.security.KeyPairGenerator;
import java.security.PrivateKey;
import java.security.Signature;
import java.security.spec.ECGenParameterSpec;
import java.security.spec.PKCS8EncodedKeySpec;
import java.util.Base64;
import java.util.Locale;
import java.util.UUID;

/**
 * Offline issuer for Mock Location license tokens.
 *
 * The private key generated by this tool must stay outside the APK and source
 * repository. The Android app only embeds the corresponding public key.
 */
public final class LicenseKeyTool {
    private static final String PRODUCT = "mock-location";
    private static final String PREFIX = "ML2";

    private LicenseKeyTool() {
    }

    public static void main(String[] args) throws Exception {
        if (args.length == 0 || "help".equalsIgnoreCase(args[0])) {
            printUsage();
            return;
        }
        if ("init".equalsIgnoreCase(args[0])) {
            init(args.length > 1 ? Paths.get(args[1]) : Paths.get("license-keys"));
            return;
        }
        if ("issue".equalsIgnoreCase(args[0])) {
            issue(args);
            return;
        }
        if ("verify".equalsIgnoreCase(args[0])) {
            verify(args);
            return;
        }
        throw new IllegalArgumentException("Unknown command: " + args[0]);
    }

    private static void init(Path directory) throws Exception {
        Files.createDirectories(directory);
        KeyPairGenerator generator = KeyPairGenerator.getInstance("EC");
        generator.initialize(new ECGenParameterSpec("secp256r1"));
        KeyPair pair = generator.generateKeyPair();
        writeBase64(directory.resolve("private-key.pk8"), pair.getPrivate().getEncoded());
        writeBase64(directory.resolve("public-key.x509"), pair.getPublic().getEncoded());
        System.out.println("Created license key pair in " + directory.toAbsolutePath());
        System.out.println("Copy the public-key.x509 value into LicenseManager.PUBLIC_KEY_B64.");
        System.out.println("Keep private-key.pk8 secret and outside the APK/repository.");
        System.out.println("PUBLIC_KEY_B64=" + encode(pair.getPublic().getEncoded()));
    }

    private static void issue(String[] args) throws Exception {
        if (args.length < 4) {
            printUsage();
            throw new IllegalArgumentException("issue requires key path, device code, expiry and features");
        }
        Path privateKeyPath = Paths.get(args[1]);
        String deviceCode = "-".equals(args[2]) ? "" : args[2].trim().toUpperCase(Locale.US);
        String expiryArgument = args[3];
        long durationDays = 0L;
        long issuedAt = System.currentTimeMillis() / 1000L;
        long expiresAt;
        if (expiryArgument.startsWith("days:")) {
            durationDays = Long.parseLong(expiryArgument.substring("days:".length()));
            if (durationDays < 0L || durationDays > 36_500L) {
                throw new IllegalArgumentException("Invalid duration days");
            }
            expiresAt = durationDays == 0L ? 0L : issuedAt + durationDays * 86_400L;
        } else {
            expiresAt = Long.parseLong(expiryArgument);
        }
        String features = args.length > 4 ? args[4] : "trajectory,route,favorite";
        String licenseId = args.length > 5 && !args[5].isEmpty()
                ? args[5] : UUID.randomUUID().toString();
        String deviceKeyId = args.length > 6 && !args[6].isEmpty()
                && !"-".equals(args[6]) ? args[6].trim().toUpperCase(Locale.US) : "";
        String payload = "{\"product\":\"" + escape(PRODUCT)
                + "\",\"licenseId\":\"" + escape(licenseId)
                + "\",\"deviceCode\":\"" + escape(deviceCode)
                + "\",\"deviceKeyId\":\"" + escape(deviceKeyId)
                + "\",\"packageName\":\"dev.drift.location"
                + "\",\"issuedAt\":" + issuedAt
                + ",\"expiresAt\":" + expiresAt
                + ",\"licenseType\":\"" + (durationDays > 0L ? "trial" : "permanent") + "\""
                + ",\"durationDays\":" + durationDays
                + ",\"features\":[" + featureJson(features) + "]}";
        PrivateKey privateKey = readPrivateKey(privateKeyPath);
        Signature signer = Signature.getInstance("SHA256withECDSA");
        signer.initSign(privateKey);
        byte[] payloadBytes = payload.getBytes(StandardCharsets.UTF_8);
        signer.update(payloadBytes);
        String token = PREFIX + "." + encode(payloadBytes) + "." + encode(signer.sign());
        System.out.println(token);
    }

    private static void verify(String[] args) throws Exception {
        if (args.length < 3) {
            printUsage();
            throw new IllegalArgumentException("verify requires public key and token");
        }
        byte[] publicKeyBytes = readBase64(Paths.get(args[1]));
        String[] parts = args[2].split("\\.", -1);
        if (parts.length != 3 || !PREFIX.equals(parts[0])) {
            throw new IllegalArgumentException("Invalid token format");
        }
        byte[] payload = decode(parts[1]);
        Signature verifier = Signature.getInstance("SHA256withECDSA");
        verifier.initVerify(KeyFactory.getInstance("EC").generatePublic(
                new java.security.spec.X509EncodedKeySpec(publicKeyBytes)));
        verifier.update(payload);
        System.out.println(verifier.verify(decode(parts[2])) ? "VALID" : "INVALID");
        System.out.println(new String(payload, StandardCharsets.UTF_8));
    }

    private static PrivateKey readPrivateKey(Path path) throws Exception {
        byte[] encoded = readBase64(path);
        return KeyFactory.getInstance("EC").generatePrivate(new PKCS8EncodedKeySpec(encoded));
    }

    private static String featureJson(String csv) {
        StringBuilder output = new StringBuilder();
        String[] values = csv.split(",");
        for (String value : values) {
            String feature = value.trim();
            if (feature.isEmpty()) continue;
            if (output.length() > 0) output.append(',');
            output.append('"').append(escape(feature)).append('"');
        }
        return output.toString();
    }

    private static String escape(String value) {
        return value.replace("\\", "\\\\").replace("\"", "\\\"")
                .replace("\n", "\\n").replace("\r", "\\r");
    }

    private static void writeBase64(Path path, byte[] bytes) throws IOException {
        Files.writeString(path, encode(bytes) + System.lineSeparator(), StandardCharsets.US_ASCII);
    }

    private static byte[] readBase64(Path path) throws IOException {
        String value = Files.readString(path, StandardCharsets.US_ASCII).trim();
        int padding = (4 - value.length() % 4) % 4;
        return Base64.getUrlDecoder().decode(value + "=".repeat(padding));
    }

    private static String encode(byte[] bytes) {
        return Base64.getUrlEncoder().withoutPadding().encodeToString(bytes);
    }

    private static byte[] decode(String value) {
        int padding = (4 - value.length() % 4) % 4;
        return Base64.getUrlDecoder().decode(value + "=".repeat(padding));
    }

    private static void printUsage() {
        System.out.println("Usage:");
        System.out.println("  java LicenseKeyTool init [directory]");
        System.out.println("  java LicenseKeyTool issue <private-key.pk8> <DEVICE_CODE|-> <EXPIRES_AT_EPOCH_SECONDS|days:N> <features> [licenseId] [DEVICE_KEY_ID| -]");
        System.out.println("  java LicenseKeyTool verify <public-key.x509> <TOKEN>");
        System.out.println("Use expiresAt 0 for a permanent license. Use '-' for an unbound test license.");
    }
}
