plugins {
    id "com.android.application"
}

android {
    namespace "dev.drift.location"
    compileSdk 36
    buildToolsVersion "35.0.0"

    defaultConfig {
        applicationId "dev.drift.location"
        minSdk 25
        targetSdk 36
        versionCode 16
        versionName "0.11.0-amap"
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    packaging {
        resources {
            merges += ["META-INF/xposed/*"]
        }
    }

    buildFeatures {
        buildConfig true
    }
}

dependencies {
    compileOnly project(":xposed-stubs")
    implementation "com.amap.api:3dmap-location-search:10.1.700_loc6.5.1_sea9.7.4"
}
