plugins {
    id "com.android.application"
}

android {
    namespace "dev.drift.location"
    compileSdk 36
    buildToolsVersion "35.0.0"

    defaultConfig {
        applicationId "dev.drift.location"
        minSdk 25
        targetSdk 36
        versionCode 21
        versionName "0.13.0-adb-auth"
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    packaging {
        resources {
            merges += ["META-INF/xposed/*"]
        }
    }

    buildFeatures {
        buildConfig true
    }
}

dependencies {
    compileOnly project(":xposed-stubs")
}
