plugins {
    id "com.android.application"
}

android {
    namespace "dev.drift.location.issuer"
    compileSdk 36
    buildToolsVersion "35.0.0"

    defaultConfig {
        applicationId "dev.drift.location.issuer"
        minSdk 25
        targetSdk 36
        versionCode 1
        versionName "1.0.0"
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    buildFeatures {
        buildConfig true
    }
}
